version: '3.8'
services:
  api:
    container_name: car_service_book_api
    image: car_service_book_api
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?schema=public
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:migrate:prod
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - teziovsky_network
    depends_on:
      - postgresql
  postgresql:
    container_name: car_service_book_postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    #    TODO: Sprawdź, gdzie się zapiszą dane z tej bazy
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - teziovsky_network
networks:
  teziovsky_network: