version: '3.8'
name: "car_service_book"
services:
  app:
    container_name: car_service_book_app
    image: car_service_book_app_prod
    build:
      dockerfile: Dockerfile
      context: ../../frontend
    ports:
      - ${APP_PORT}:3000
    networks:
      - car_service_book_network
    depends_on:
      - api
  api:
    container_name: car_service_book_api
    image: car_service_book_api_prod
    build:
      dockerfile: Dockerfile
      context: ../../backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?schema=public
    env_file:
      - ../../.env
    ports:
      - ${API_PORT}:3000
    networks:
      - car_service_book_network
    depends_on:
      - postgresql
  postgresql:
    container_name: car_service_book_postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ../../.env
    #    TODO: Sprawdź, gdzie się zapiszą dane z tej bazy
    volumes:
      - ../../database/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    networks:
      - car_service_book_network
networks:
  car_service_book_network:
