version: '3.8'
services:
  api:
    container_name: car_service_book_api_stage
    image: car_service_book_api_stage
    build:
      dockerfile: Dockerfile
      context: ../../
      target: development
    env_file:
      - ../../.env.stage
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ../../.:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - teziovsky_network
    depends_on:
      - postgresql
  postgresql:
    container_name: car_service_book_postgresql_stage
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - car_service_book_postgresql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - teziovsky_network
volumes:
  car_service_book_postgresql:
    driver: local
networks:
  teziovsky_network: